### ISSUE TITLE
Can't get video to play on iOS

### ISSUE THREAD

**Issue by drejohnson** [NamPNQ/bower-videogular-youtube#46] opened 2015-10-20 19:42 UTC
Here's my code pen if that helps. Videogular without the Youtube plugin works fine.

**Comment by 2fdevs** [comment] 2015-10-23 10:14
Can yuo post the codepen again? It seems that github cut it. :P

**Comment by drejohnson** [comment] 2015-10-23 12:27
Here it is: http://codepen.io/drejohnson/pen/ZbvEoQ

**Comment by el-rotny** [comment] 2015-10-29 06:41
I'm having the same issues. Checked out the codepen and same deal.

**Comment by rubenCodeforges** [comment] 2015-10-29 11:02
@2fdevs  any progress on that ?
i cant reproduce it without iOS , linux seems ok  , can be some browser specific issues
i mean safari , dont know is it still on webkit or not .

**Comment by rubenCodeforges** [comment] 2015-10-29 11:12
Opera works fine

**Comment by NamPNQ** [comment] 2015-10-29 11:15
As i remember, in ios , youtube iframe need bring to top to work, @rubenCodeforges Can you show we the message show in console when run in ios

**Comment by rubenCodeforges** [comment] 2015-10-29 11:17
@NamPNQ sorry buddy i dont have iOS , but @el-rotny  has , its now but night in usa , so he will be back like in 8 hours

**Comment by rubenCodeforges** [comment] 2015-10-29 11:17
@NamPNQ  BTW android and all available browser for it , works fine

**Comment by el-rotny** [comment] 2015-10-29 17:43
@NamPNQ  ```WebGL: INVALID_ENUM: getParameter: invalid parameter name, WEBGL_debug_renderer_info not enabled``` is not an error, it's a warning on html5player. No errors on the console as of now.  The video shows "if playback doesn't begin shortly, try restarting your device" @rubenCodeforges  we should note that we added the Vimeo support. Is there a fork everyone can try out?

**Comment by rubenCodeforges** [comment] 2015-10-29 17:47
@el-rotny ive provided guys with the code , but vimeo is not firing when we are handling a youtube url

**Comment by 2fdevs** [comment] 2015-10-29 20:01
@rubenCodeforges @el-rotny I haven't got time to take a look to this issue yet, I'm pretty busy this last two weeks at work. That WebGL error is quite weird and it looks to me a Youtube error more than a Videogular error.

Not all Youtube videos plays well on all devices, specially if it's an old video. Did you tried playing that Youtube video in Youtube website on iOS?

**Comment by el-rotny** [comment] 2015-11-05 08:22
@drejohnson did you find a solution you can share?

**Comment by rubenCodeforges** [comment] 2015-11-05 12:05
@2fdevs  hi seems like on ios the controls of videogular are blocked and thats why we cant play the video. 
A solution is to disable vg-controlls and overlay-play and other overlays , so that the youtube player is native. its a fallback but thanks to iOS devs for this sht

**Comment by el-rotny** [comment] 2015-11-11 19:19
For anyone coming across this issue. This plugin is not compatible with https://github.com/videogular/bower-videogular-overlay-play on iOS. The protocols to play videos need to be initiated by user directly on the iframe rather than programmatically. Also, the controls from videogular wont initiate the player. What we did to combat this issue, is to hide the controls on `API.currentState` is equal to `stop` and hiding the overlay on the same state, only when on iOS. Once the video is played, the controls will be available on hover if you have that setting enabled.

**Comment by NamPNQ** [comment] 2016-01-25 11:42
No any update more. I close this issuse. if you have more questions, we can reopen ticket.

**Closed by NamPNQ** 2016-01-25 11:42 UTC
